import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { NavLink } from 'react-router-dom';
import { CheckCircle2, Clock3, MessageSquareText, PhoneCall, RefreshCw, Search, Users, X } from 'lucide-react';
import { api } from './lib/api';
import { statusSiriusLabel } from './lib/agenda';
import { TipoInteracaoRadio } from './components/TipoInteracaoRadio';

type Vendedor = { id: string; nome: string; filialCodigo: number; ativo: boolean };
type Evento = { codigo: number; vendedorId: string; vendedorNome: string; clienteNome: string; clienteCodigo: number; cidade: string; dia: string; inicio: number; fim: number; horarioIndefinido: boolean; status: string; tipoInteracao: string; contato: string; observacao: string; versao: string };
type Ocorrencia = { codigo: number; descricao: string; tipo: string };
type Atendimento = { id: string; vendedorId: string; agendaCodigo: number; estado: string; dados: { agenda: { cliente: number; dia: string; inicio: number; fim: number; status: string }; ocorrencia: Ocorrencia; payload: { contato: string; observacao: string; tipoInteracao: string; horaAgenda: string } }; resultado?: { mensagem: string }; criadoEm: string };
type AgendaResposta = { eventos: Evento[]; vendedores: Vendedor[]; falhas: { vendedorId: string; vendedorNome: string; mensagem: string }[]; parcial: boolean; atualizadoEm: string };
const hoje = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Sao_Paulo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
const dataBr = (d: string) => d.split('-').reverse().join('/');
const horario = (n: number) => n === 1440 ? '24:00' : `${String(Math.floor(n / 60)).padStart(2, '0')}:${String(n % 60).padStart(2, '0')}`;

export default function AgendaCrm() {
  const [data, setData] = useState(hoje), [vendedorId, setVendedor] = useState(''), [visao, setVisao] = useState<'equipe' | 'vendedor'>('equipe');
  const [agenda, setAgenda] = useState<AgendaResposta>(), [ocorrencias, setOcorrencias] = useState<Ocorrencia[]>([]), [atendimentos, setAtendimentos] = useState<Atendimento[]>([]);
  const [busca, setBusca] = useState(''), [loading, setLoading] = useState(false), [erro, setErro] = useState(''), [mensagem, setMensagem] = useState(''), [versao, setVersao] = useState(0), [selecionado, setSelecionado] = useState<Evento>();
  useEffect(() => {
    const controller = new AbortController(); setErro(''); setAgenda(undefined);
    if (visao === 'vendedor' && !vendedorId) return () => controller.abort();
    setLoading(true); const filtro = new URLSearchParams({ inicio: data, fim: data, ...(vendedorId ? { vendedorId } : {}) });
    Promise.all([
      api<AgendaResposta>(`/agenda/eventos?${filtro}`, { signal: controller.signal }),
      api<{ ocorrencias: Ocorrencia[] }>(`/agenda/crm/ocorrencias${vendedorId ? `?vendedorId=${encodeURIComponent(vendedorId)}` : ''}`, { signal: controller.signal }),
      api<{ atendimentos: Atendimento[] }>(`/agenda/crm/atendimentos?${filtro}`, { signal: controller.signal }),
    ]).then(([a, o, r]) => { if (!controller.signal.aborted) { setAgenda(a); setOcorrencias(o.ocorrencias); setAtendimentos(r.atendimentos); } }).catch(e => { if (!controller.signal.aborted) setErro(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [data, vendedorId, visao, versao]);
  const ultimo = new Map<number, Atendimento>(); atendimentos.forEach(a => { if (!ultimo.has(a.agendaCodigo)) ultimo.set(a.agendaCodigo, a); });
  const eventos = (agenda?.eventos || []).filter(e => `${e.clienteNome} ${e.vendedorNome} ${e.cidade} ${e.contato}`.toLowerCase().includes(busca.toLowerCase()));
  const fazer = eventos.filter(e => !ultimo.has(e.codigo)), concluidos = eventos.filter(e => ultimo.get(e.codigo)?.estado === 'CONCLUIDO'), incertos = eventos.filter(e => ['INCERTO', 'ENVIANDO'].includes(ultimo.get(e.codigo)?.estado || ''));
  const vendedor = agenda?.vendedores.find(v => v.id === vendedorId);
  return <>
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-brand-600">Central de relacionamento</p><h1 className="mt-2 text-3xl font-semibold">Operar agenda</h1><p className="mt-2 text-sm text-slate-500">Trate os contatos do dia, registre a ocorrência e mantenha o histórico no Sírius.</p></div><div className="flex gap-2"><NavLink className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium" to="/agenda">Visualizar calendário</NavLink><NavLink className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium" to="/agenda/planejar">Planejar contatos</NavLink></div></div>
    <section className="card mb-5 p-4"><div className="flex flex-wrap items-end gap-3"><div className="flex rounded-xl bg-slate-100 p-1" role="group" aria-label="Escopo da operação"><button aria-pressed={visao === 'equipe'} className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm ${visao === 'equipe' ? 'bg-white font-semibold shadow-sm' : 'text-slate-500'}`} onClick={() => { setVisao('equipe'); setVendedor(''); }}><Users size={17} />Equipe</button><button aria-pressed={visao === 'vendedor'} className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm ${visao === 'vendedor' ? 'bg-white font-semibold shadow-sm' : 'text-slate-500'}`} onClick={() => setVisao('vendedor')}><PhoneCall size={17} />Vendedor</button></div><label className="text-xs text-slate-500">Dia da operação<input className="field mt-1" type="date" value={data} onChange={e => e.target.value && setData(e.target.value)} /></label><label className="min-w-64 text-xs text-slate-500">Vendedor<select className="field mt-1" value={vendedorId} onChange={e => setVendedor(e.target.value)}><option value="">{visao === 'equipe' ? 'Todos da filial' : 'Selecione'}</option>{(agenda?.vendedores || []).map(v => <option key={v.id} value={v.id}>{v.nome}{!v.ativo ? ' (inativo)' : ''}</option>)}</select></label><button className="ml-auto flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm" disabled={loading} onClick={() => setVersao(v => v + 1)}><RefreshCw size={16} className={loading ? 'animate-spin' : ''} />Atualizar fila</button></div><div className="mt-4 flex items-center gap-2 border-t border-slate-100 pt-4"><Search size={18} className="text-slate-400" /><input className="w-full bg-transparent py-2 text-sm outline-none" aria-label="Buscar na fila" placeholder="Buscar cliente, vendedor, cidade ou contato" value={busca} onChange={e => setBusca(e.target.value)} /></div></section>
    {mensagem && <p role="status" className="mb-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">{mensagem}</p>}
    {erro && <p role="alert" className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{erro} <NavLink to="/configuracao" className="underline">Conectar ao Sírius</NavLink></p>}
    {agenda?.parcial && <div role="alert" className="mb-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Fila parcial: {agenda.falhas.map(f => f.vendedorNome).join(', ')} não pôde ser consultado.</div>}
    {loading ? <div className="card grid min-h-60 place-items-center text-sm text-slate-500"><RefreshCw className="animate-spin text-brand-600" /></div> : visao === 'vendedor' && !vendedorId ? <div className="card p-12 text-center text-sm text-slate-500"><PhoneCall className="mx-auto mb-3" />Selecione um vendedor para começar a operação.</div> : agenda && <>
      <div className="mb-4 grid gap-3 sm:grid-cols-4"><Resumo label="Dia" value={dataBr(data)} /><Resumo label="Escopo" value={vendedor?.nome || 'Equipe da filial'} /><Resumo label="A fazer" value={fazer.length} /><Resumo label="Registrados / conferir" value={`${concluidos.length} / ${incertos.length}`} /></div>
      <div className="grid items-start gap-5 xl:grid-cols-3"><Coluna titulo="A fazer" subtitulo="Contatos ainda sem atendimento registrado" icone={<Clock3 size={18} />} itens={fazer} vazio="Nenhum contato pendente no filtro." onSelect={setSelecionado} /><Coluna titulo="Atendidos" subtitulo="Registros enviados com sucesso" icone={<CheckCircle2 size={18} />} itens={concluidos} atendimentos={ultimo} vazio="Nenhum atendimento registrado." onSelect={setSelecionado} /><Coluna titulo="Conferir no Sírius" subtitulo="Envios sem confirmação segura" icone={<MessageSquareText size={18} />} itens={incertos} atendimentos={ultimo} vazio="Nenhuma pendência de confirmação." onSelect={setSelecionado} /></div>
      {!eventos.length && <p className="card mt-4 p-10 text-center text-sm text-slate-500">Nenhum agendamento retornado para {dataBr(data)} e estes filtros.</p>}
      <p className="mt-4 text-xs text-slate-400">A ocorrência é carregada diretamente da tabela do Sírius. O histórico desta tela registra os envios feitos pelo Gerente Comercial.</p>
    </>}
    {selecionado && <AtendimentoDialog evento={selecionado} ocorrencias={ocorrencias} anterior={ultimo.get(selecionado.codigo)} onClose={() => setSelecionado(undefined)} onConcluir={r => { setSelecionado(undefined); setMensagem(r.resultado?.mensagem || 'Atendimento enviado.'); setVersao(v => v + 1); }} />}
  </>;
}
function Resumo({ label, value }: { label: string; value: string | number }) { return <div className="card p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 truncate text-lg font-semibold">{value}</p></div>; }
function Coluna({ titulo, subtitulo, icone, itens, atendimentos, vazio, onSelect }: { titulo: string; subtitulo: string; icone: ReactNode; itens: Evento[]; atendimentos?: Map<number, Atendimento>; vazio: string; onSelect: (e: Evento) => void }) { return <section className="rounded-2xl bg-slate-100/80 p-3"><div className="mb-3 flex items-start gap-2 px-1"><span className="mt-0.5 text-brand-700">{icone}</span><div><h2 className="font-semibold">{titulo} <span className="text-slate-400">{itens.length}</span></h2><p className="text-xs text-slate-500">{subtitulo}</p></div></div><div className="space-y-3">{itens.map(e => { const a = atendimentos?.get(e.codigo); return <button key={`${e.vendedorId}:${e.codigo}`} onClick={() => onSelect(e)} className="w-full rounded-xl border border-slate-200 bg-white p-4 text-left shadow-sm hover:border-brand-400"><div className="flex items-start justify-between gap-2"><strong>{e.horarioIndefinido ? 'Horário indefinido' : `${horario(e.inicio)}–${horario(e.fim)}`}</strong><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] text-slate-500">#{e.codigo}</span></div><p className="mt-3 font-semibold">{e.clienteNome}</p><p className="mt-1 text-xs text-slate-500">{e.vendedorNome}{e.cidade ? ` · ${e.cidade}` : ''}</p><p className="mt-2 text-xs text-slate-500">{a ? `${a.dados.ocorrencia.descricao} · ${a.estado}` : `${statusSiriusLabel(e.status)} · ${e.tipoInteracao || 'Interação não informada'}`}</p>{a?.dados.payload.observacao && <p className="mt-2 line-clamp-2 text-xs text-slate-600">{a.dados.payload.observacao}</p>}</button>; })}{!itens.length && <p className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-xs text-slate-500">{vazio}</p>}</div></section>; }

function AtendimentoDialog({ evento, ocorrencias, anterior, onClose, onConcluir }: { evento: Evento; ocorrencias: Ocorrencia[]; anterior?: Atendimento; onClose: () => void; onConcluir: (r: Atendimento) => void }) {
  const [loading, setLoading] = useState(false), [erro, setErro] = useState('');
  const grupos = [...new Set(ocorrencias.map(o => o.tipo).filter(Boolean))].sort();
  async function salvar(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setErro(''); const f = new FormData(e.currentTarget); try { const r = await api<Atendimento>(`/agenda/eventos/${evento.codigo}/atendimentos`, { method: 'POST', body: JSON.stringify({ chave: crypto.randomUUID(), vendedorId: evento.vendedorId, versao: evento.versao, diaAgenda: evento.dia, codigoOcorrencia: Number(f.get('codigoOcorrencia')), contato: f.get('contato'), observacao: f.get('observacao'), tipoInteracao: f.get('tipoInteracao') }) }); onConcluir(r); } catch (e) { setErro((e as Error).message); } finally { setLoading(false); } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><section role="dialog" aria-modal="true" aria-labelledby="crm-dialog-title" className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-brand-600">Atendimento da agenda</p><h2 id="crm-dialog-title" className="mt-1 text-xl font-semibold">{evento.clienteNome}</h2></div><button aria-label="Fechar atendimento" onClick={onClose}><X size={22} /></button></div><div className="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 text-sm sm:grid-cols-2"><p><span className="block text-xs text-slate-400">Vendedor</span>{evento.vendedorNome}</p><p><span className="block text-xs text-slate-400">Agenda</span>{dataBr(evento.dia)} · {horario(evento.inicio)}–{horario(evento.fim)}</p><p><span className="block text-xs text-slate-400">Contato atual</span>{evento.contato || 'Não informado'}</p><p><span className="block text-xs text-slate-400">Status / interação</span>{statusSiriusLabel(evento.status, '—')} · {evento.tipoInteracao || '—'}</p></div>
    {anterior ? <div className={`mt-4 rounded-xl p-4 text-sm ${anterior.estado === 'CONCLUIDO' ? 'bg-emerald-50 text-emerald-900' : 'bg-amber-50 text-amber-900'}`}><strong>{anterior.dados.ocorrencia.descricao} · {anterior.estado}</strong><p className="mt-2 whitespace-pre-wrap">{anterior.dados.payload.observacao}</p><p className="mt-2 text-xs">Registrado em {new Date(anterior.criadoEm).toLocaleString('pt-BR')} por {anterior.dados.payload.contato}.</p>{anterior.estado !== 'CONCLUIDO' && <p className="mt-2 font-medium">Confira no Sírius antes de tentar outro registro.</p>}</div> : <form onSubmit={salvar} className="mt-5 space-y-4"><label className="block text-sm font-medium">Ocorrência<select autoFocus required className="field mt-1" name="codigoOcorrencia"><option value="">Selecione o resultado do contato</option>{grupos.map(g => <optgroup key={g} label={g}>{ocorrencias.filter(o => o.tipo === g).map(o => <option key={o.codigo} value={o.codigo}>{o.descricao}</option>)}</optgroup>)}{ocorrencias.filter(o => !o.tipo).map(o => <option key={o.codigo} value={o.codigo}>{o.descricao}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Pessoa contatada<input required className="field mt-1" name="contato" defaultValue={evento.contato} maxLength={200} placeholder="Nome ou setor" /></label><TipoInteracaoRadio defaultValue={evento.tipoInteracao === 'P' ? 'P' : 'R'} /></div><label className="block text-sm font-medium">Resumo do atendimento<textarea required className="field mt-1" name="observacao" rows={5} minLength={3} maxLength={4000} placeholder="Registre o que foi conversado, próximos passos e informações úteis para o próximo contato." /></label>{erro && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{erro}</p>}<div className="flex justify-end gap-3 border-t border-slate-100 pt-4"><button type="button" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm" onClick={onClose}>Cancelar</button><button className="btn-primary" disabled={loading}>{loading ? 'Registrando⬦' : 'Registrar atendimento no Sírius'}</button></div><p className="text-xs text-slate-500">Se a conexão cair após o envio, o registro ficará como incerto e não será reenviado automaticamente.</p></form>}
    {anterior && <div className="mt-4 text-right"><button className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm" onClick={onClose}>Fechar</button></div>}</section></div>;
}

