import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import {
  ArrowRight, BarChart3, BrainCircuit, CalendarCheck2, Check, ChevronDown,
  CircleDollarSign, Clock3, DatabaseZap, Download, Eye, Lightbulb, Pencil, ShieldCheck,
  Target, TrendingDown, Users, X,
} from 'lucide-react';
import { api } from './lib/api';

type Props = { user: { nome: string } | null };

const recursos = [
  { icon: DatabaseZap, titulo: 'Dados conectados ao Sírius', texto: 'Sincroniza vendedores, clientes, vendas, produtos e itens para formar uma base comercial única e confiável.' },
  { icon: BarChart3, titulo: 'Visão clara da operação', texto: 'Consolida faturamento, ticket médio, clientes ativos, potencial estimado e desempenho por vendedor e período.' },
  { icon: Target, titulo: 'Oportunidades priorizadas', texto: 'Organiza a carteira por urgência e potencial, com a explicação dos dados que levaram a cada recomendação.' },
  { icon: CalendarCheck2, titulo: 'Agenda comercial orientada', texto: 'Transforma oportunidades em contatos, respeitando capacidade, horários, intervalos e compromissos já existentes.' },
];

const analises = [
  { numero: '01', icon: Clock3, titulo: 'Recompra atrasada', texto: 'Calcula o intervalo típico entre compras de cada cliente ou produto. Quando o comportamento foge desse padrão, sinaliza o atraso e estima quantidade e valor potencial.' },
  { numero: '02', icon: TrendingDown, titulo: 'Cliente em queda', texto: 'Compara o desempenho recente com o histórico anterior para identificar redução relevante de volume antes que a conta seja perdida.' },
  { numero: '03', icon: BrainCircuit, titulo: 'Prioridade explicável', texto: 'Combina atraso, frequência, valor médio, queda e recorrência em uma pontuação de 0 a 100. Toda recomendação mostra sua justificativa.' },
];

export default function Apresentacao({ user }: Props) {
  const [prazo, setPrazo] = useState<string | null>(null);
  const [editando, setEditando] = useState(false);
  const [precoAberto, setPrecoAberto] = useState(false);
  const [mensagem, setMensagem] = useState('');
  const [salvando, setSalvando] = useState(false);

  useEffect(() => { api<{ prazoDesenvolvimento: string | null }>('/produto/apresentacao').then(r => setPrazo(r.prazoDesenvolvimento)); }, []);

  async function salvarPrazo(evento: FormEvent<HTMLFormElement>) {
    evento.preventDefault();
    setSalvando(true); setMensagem('');
    const valor = String(new FormData(evento.currentTarget).get('prazoDesenvolvimento') || '');
    try {
      const resposta = await api<{ prazoDesenvolvimento: string | null }>('/produto/apresentacao', { method: 'PATCH', body: JSON.stringify({ prazoDesenvolvimento: valor }) });
      setPrazo(resposta.prazoDesenvolvimento); setEditando(false); setMensagem('Prazo atualizado.');
    } catch (erro) { setMensagem((erro as Error).message); }
    finally { setSalvando(false); }
  }

  return <main className="presentation min-h-screen bg-[#f7f8fb] text-[#050214]">
    <nav className="sticky top-0 z-30 border-b border-white/10 bg-[#00236a]/95 text-white backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-8">
        <a href="#inicio" className="flex items-center gap-3"><img src="/brand/space-sistemas.webp" alt="Space Sistemas" className="h-9 w-auto"/><span className="border-l border-white/20 pl-3"><strong className="block leading-tight">Gerente Comercial</strong><span className="text-xs text-white/55">Inteligência de carteira</span></span></a>
        <div className="hidden items-center gap-7 text-sm font-medium md:flex"><a href="#solucao">A solução</a><a href="#analises">Como analisa</a><a href="#participacao">Condições</a></div>
        <div className="flex items-center gap-2"><button onClick={()=>window.print()} className="screen-only hidden items-center gap-2 rounded-full border border-white/25 px-4 py-2.5 text-sm font-semibold sm:inline-flex"><Download size={16}/> Gerar PDF</button><Link to="/" className="inline-flex items-center gap-2 rounded-full bg-[#ff7b00] px-4 py-2.5 text-sm font-semibold text-white">{user ? 'Abrir plataforma' : 'Acessar demonstração'}<ArrowRight size={16}/></Link></div>
      </div>
    </nav>

    <section id="inicio" className="relative overflow-hidden px-5 pb-20 pt-20 md:px-8 md:pb-28 md:pt-28">
      <div className="presentation-grid absolute inset-0 opacity-40"/><div className="absolute -right-40 top-24 size-[34rem] rounded-full bg-[#ffb000]/20 blur-3xl"/>
      <div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.1fr_.9fr]">
        <div><span className="inline-flex items-center gap-2 rounded-full border border-[#00236a]/15 bg-white/70 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-[#00236a]"><Lightbulb size={15}/> Decisões comerciais guiadas por dados</span><h1 className="mt-7 max-w-4xl text-5xl font-semibold leading-[.98] tracking-[-.055em] md:text-7xl">Sua equipe sabendo <span className="text-[#164b9c]">quem procurar, por quê e quando.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#5d6878]">O Gerente Comercial transforma o histórico de vendas em oportunidades objetivas, organiza a rotina dos vendedores e ajuda a agir antes que bons clientes se afastem.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/" className="inline-flex items-center gap-2 rounded-full bg-[#ff7b00] px-6 py-3.5 font-bold text-white">Ver a ferramenta funcionando <ArrowRight size={18}/></Link><a href="#analises" className="inline-flex items-center gap-2 rounded-full border border-[#00236a]/20 px-6 py-3.5 font-semibold text-[#00236a]">Entender as análises <ChevronDown size={18}/></a></div></div>
        <div className="relative"><div className="rounded-[2rem] border border-white/70 bg-[#00236a] p-5 shadow-2xl shadow-[#00236a]/20 md:p-7"><div className="mb-7 flex items-center justify-between text-white"><div><p className="text-xs uppercase tracking-[.18em] text-[#d5d8dc]">Visão comercial</p><p className="mt-1 text-xl font-semibold">O que merece atenção agora</p></div><span className="size-3 rounded-full bg-[#ffb000] shadow-[0_0_18px_#ffb000]"/></div><div className="grid grid-cols-2 gap-3"><MiniCard rotulo="Oportunidades" valor="24" destaque/><MiniCard rotulo="Potencial estimado" valor="R$ 86 mil"/><MiniCard rotulo="Recompras atrasadas" valor="11"/><MiniCard rotulo="Clientes em risco" valor="7"/></div><div className="mt-4 rounded-2xl bg-white/8 p-4"><div className="flex items-end gap-2">{[42,68,50,84,62,92,76].map((altura,i)=><span key={i} className={`flex-1 rounded-t-md ${i===5?'bg-[#ff7b00]':'bg-white/25'}`} style={{height:altura}}/>)}</div><div className="mt-3 flex justify-between text-[10px] uppercase tracking-wider text-white/45"><span>Histórico</span><span>Hoje</span></div></div></div></div>
      </div>
    </section>

    <section id="solucao" className="bg-[#00236a] px-5 py-20 text-white md:px-8 md:py-28"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#ffb000]">Da informação à ação</p><div className="mt-4 grid gap-8 lg:grid-cols-2"><h2 className="text-4xl font-semibold tracking-[-.04em] md:text-6xl">Menos planilhas.<br/>Mais direção comercial.</h2><p className="max-w-xl text-lg leading-8 text-[#d5d8dc]">A plataforma lê o comportamento real de compra, encontra sinais que se perdem no dia a dia e entrega uma fila de trabalho clara para gestão e vendas.</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-3xl bg-white/10 md:grid-cols-2 lg:grid-cols-4">{recursos.map(({icon:Icon,titulo,texto})=><article key={titulo} className="bg-[#00236a] p-7"><span className="grid size-12 place-items-center rounded-2xl bg-white/8 text-[#ffb000]"><Icon/></span><h3 className="mt-7 text-xl font-semibold">{titulo}</h3><p className="mt-3 leading-7 text-[#d5d8dc]">{texto}</p></article>)}</div></div></section>

    <section id="analises" className="px-5 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#164b9c]">Como a análise funciona</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] md:text-6xl">Critérios objetivos.<br/>Recomendações compreensíveis.</h2><p className="mt-6 text-lg leading-8 text-[#5d6878]">Os cálculos usam o histórico sincronizado da própria empresa. Não há recomendação aleatória: cada alerta nasce de padrões mensuráveis.</p></div><div className="mt-14 divide-y divide-[#00236a]/15 border-y border-[#00236a]/15">{analises.map(({numero,icon:Icon,titulo,texto})=><article key={numero} className="grid gap-5 py-8 md:grid-cols-[70px_70px_1fr_1.4fr] md:items-center"><span className="text-sm font-bold text-[#69727d]">{numero}</span><span className="grid size-12 place-items-center rounded-full bg-[#eef3fb] text-[#00236a]"><Icon size={21}/></span><h3 className="text-2xl font-semibold">{titulo}</h3><p className="leading-7 text-[#5d6878]">{texto}</p></article>)}</div><div className="mt-8 flex items-start gap-3 rounded-2xl bg-[#eef3fb] p-5 text-sm leading-6 text-[#3f4b5c]"><ShieldCheck className="mt-0.5 shrink-0 text-[#00236a]" size={20}/><p><strong>Dados sob controle.</strong> A operação é feita sobre uma base local sincronizada. Credenciais do Sírius não são expostas ao navegador e a senha da integração não é armazenada.</p></div></div></section>

    <section id="participacao" className="bg-[#eef3fb] px-5 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#164b9c]">Grupo inicial de clientes</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Participe da construção de uma ferramenta feita para a operação real.</h2><p className="mt-6 leading-7 text-[#5d6878]">O desenvolvimento será iniciado após a formação de um grupo mínimo de 10 clientes com compromisso de aquisição.</p></div><div className="space-y-4"><Condition numero="10" titulo="clientes para iniciar" texto="O ciclo de desenvolvimento começa quando o grupo mínimo de clientes participantes estiver confirmado."/><Condition numero={prazo || 'A definir'} titulo="prazo de desenvolvimento" texto="O cronograma será informado após o fechamento do grupo e a definição do escopo final." editavel={Boolean(user)} onEdit={()=>setEditando(true)}/><Condition numero="60 dias" titulo="de participação assistida" texto="Após a instalação, cada cliente terá 60 dias para testar e sugerir melhorias, com análise e resposta mais rápidas."/></div></div><div className="mt-8 rounded-3xl border border-[#00236a]/10 bg-white/75 p-6 md:p-8"><div className="flex gap-4"><Check className="mt-1 shrink-0 text-[#ff7b00]"/><div><h3 className="text-lg font-semibold">Sobre as sugestões de funcionalidades</h3><p className="mt-2 leading-7 text-[#5d6878]">Todas as sugestões serão avaliadas pelo desenvolvedor quanto à viabilidade, aderência ao produto, segurança e impacto no projeto. Por isso, poderão ou não ser implementadas.</p></div></div></div>{mensagem&&<p className="mt-4 text-sm font-medium text-[#164b9c]">{mensagem}</p>}</div></section>

    <section className="px-5 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-4xl text-center"><Eye className="mx-auto text-[#ff7b00]" size={28}/><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em] md:text-5xl">Quer conhecer as condições comerciais?</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-[#5d6878]">O investimento fica separado desta apresentação para ser mostrado no momento adequado da conversa.</p><button onClick={()=>setPrecoAberto(true)} className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#ff7b00] px-7 py-4 font-semibold text-white"><CircleDollarSign size={19}/> Ver investimento</button></div></section>

    <section className="print-only px-10 py-16"><div className="mx-auto max-w-4xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#164b9c]">Condições comerciais</p><h2 className="mt-4 text-5xl font-semibold">Investimento</h2><div className="mt-10 grid grid-cols-2 gap-5"><div className="rounded-3xl bg-[#eef3fb] p-7"><p className="text-[#5d6878]">Aquisição da plataforma</p><p className="mt-4 text-4xl font-semibold">R$ 4.863</p><p className="mt-3 text-sm text-[#69727d]">Equivalente a três salários mínimos no valor de referência atual.</p></div><div className="rounded-3xl bg-[#00236a] p-7 text-white"><p className="text-[#d5d8dc]">Manutenção mensal</p><p className="mt-4 text-4xl font-semibold">R$ 40</p><p className="mt-3 text-sm text-[#d5d8dc]">por vendedor cadastrado</p></div></div><p className="mt-8 leading-7 text-[#5d6878]">As condições apresentadas fazem parte desta etapa de validação de mercado e devem ser confirmadas na formalização da proposta.</p></div></section>

    <footer className="border-t border-[#00236a]/10 px-5 py-8 md:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 text-sm text-[#5d6878]"><span>Space Sistemas · Gerente Comercial</span><Link className="font-semibold text-[#00236a]" to="/">Acessar demonstração →</Link></div></footer>

    {precoAberto&&<div className="fixed inset-0 z-50 grid place-items-center bg-[#050214]/80 p-5 backdrop-blur-sm" onMouseDown={e=>{if(e.currentTarget===e.target)setPrecoAberto(false)}}><div role="dialog" aria-modal="true" aria-labelledby="preco-titulo" className="w-full max-w-xl rounded-[2rem] bg-[#f7f8fb] p-7 shadow-2xl md:p-10"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#164b9c]">Condições comerciais</p><h2 id="preco-titulo" className="mt-2 text-3xl font-semibold">Investimento</h2></div><button aria-label="Fechar" onClick={()=>setPrecoAberto(false)} className="grid size-10 place-items-center rounded-full border border-[#00236a]/15"><X size={19}/></button></div><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-white p-5"><p className="text-sm text-[#5d6878]">Aquisição da plataforma</p><p className="mt-3 text-3xl font-semibold">R$ 4.863</p><p className="mt-2 text-xs leading-5 text-[#69727d]">Equivalente a três salários mínimos no valor de referência atual.</p></div><div className="rounded-2xl bg-[#00236a] p-5 text-white"><p className="text-sm text-[#d5d8dc]">Manutenção mensal</p><p className="mt-3 text-3xl font-semibold">R$ 40</p><p className="mt-2 text-xs text-[#d5d8dc]">por vendedor cadastrado</p></div></div><p className="mt-6 text-sm leading-6 text-[#5d6878]">As condições apresentadas fazem parte desta etapa de validação de mercado e devem ser confirmadas na formalização da proposta.</p></div></div>}

    {editando&&<div className="fixed inset-0 z-50 grid place-items-center bg-[#050214]/80 p-5 backdrop-blur-sm"><form onSubmit={salvarPrazo} className="w-full max-w-md rounded-3xl bg-white p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#164b9c]">Configuração</p><h2 className="mt-2 text-2xl font-semibold">Prazo de desenvolvimento</h2></div><button type="button" onClick={()=>setEditando(false)}><X/></button></div><label className="mt-7 block text-sm font-medium">Prazo exibido<input autoFocus name="prazoDesenvolvimento" defaultValue={prazo || ''} maxLength={120} placeholder="Ex.: 6 meses após a confirmação" className="field mt-2"/></label><p className="mt-2 text-xs text-slate-500">Deixe em branco para exibir “A definir”.</p><button disabled={salvando} className="btn-primary mt-6 w-full">{salvando?'Salvando…':'Salvar prazo'}</button></form></div>}
  </main>;
}

function MiniCard({rotulo,valor,destaque=false}:{rotulo:string;valor:string;destaque?:boolean}) { return <div className={`rounded-2xl p-4 ${destaque?'bg-[#ffb000] text-[#050214]':'bg-white/8 text-white'}`}><p className={`text-xs ${destaque?'text-[#00236a]':'text-white/55'}`}>{rotulo}</p><p className="mt-2 text-2xl font-semibold">{valor}</p></div>; }
function Condition({numero,titulo,texto,editavel,onEdit}:{numero:string;titulo:string;texto:string;editavel?:boolean;onEdit?:()=>void}) { return <article className="rounded-3xl bg-white p-6 shadow-sm md:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-3xl font-semibold tracking-tight text-[#00236a]">{numero}</p><h3 className="mt-1 text-sm font-bold uppercase tracking-[.12em] text-[#164b9c]">{titulo}</h3></div>{editavel&&<button onClick={onEdit} className="inline-flex items-center gap-1.5 rounded-full border border-[#00236a]/15 px-3 py-2 text-xs font-semibold text-[#00236a]"><Pencil size={13}/> Editar</button>}</div><p className="mt-4 leading-7 text-[#5d6878]">{texto}</p></article>; }
